basePath: /api/v1
definitions:
  odontologo.OdontologoRequest:
    properties:
      apellido:
        description: ID        int    `json:"id"`
        type: string
      matricula:
        type: string
      nombre:
        type: string
    type: object
  paciente.PacienteRequest:
    properties:
      apellido:
        type: string
      dni:
        type: string
      domicilio:
        type: string
      fecha_alta:
        type: string
      nombre:
        type: string
    type: object
  turno.TurnoDniMatriculaRequest:
    properties:
      descripcion:
        type: string
      dni_paciente:
        type: string
      fecha_hora:
        type: string
      matricula_odontologo:
        type: string
    type: object
  turno.TurnoRequest:
    properties:
      descripcion:
        type: string
      fecha_hora:
        type: string
      id_odontologo:
        type: integer
      id_paciente:
        type: integer
    type: object
  web.errorResponse:
    properties:
      code:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  web.response:
    properties:
      data: {}
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Documentacion de la clinica odontologica
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Clinica Odontologica API
  version: "1.0"
paths:
  /odontologos:
    post:
      consumes:
      - application/json
      description: Create a new odontologo
      parameters:
      - description: Add odontologo
        in: body
        name: Odontologo
        required: true
        schema:
          $ref: '#/definitions/odontologo.OdontologoRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Create Odontologo
      tags:
      - odontologo
  /odontologos/:id:
    delete:
      consumes:
      - application/json
      description: Delete odontologo by id
      parameters:
      - description: id del odontologo
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: delete odontologo
      tags:
      - odontologo
    get:
      consumes:
      - application/json
      description: Get odontologo by id
      parameters:
      - description: id del odontologo
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: get odontologo
      tags:
      - odontologo
    put:
      consumes:
      - application/json
      description: Update odontologo by id
      parameters:
      - description: Update odontologo
        in: body
        name: Odontologo
        required: true
        schema:
          $ref: '#/definitions/odontologo.OdontologoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: update odontologo
      tags:
      - odontologo
  /odontologos/patch/:id:
    patch:
      consumes:
      - application/json
      description: Update odontologo for field
      parameters:
      - description: Update odontologo for field
        in: body
        name: Odontologo
        required: true
        schema:
          $ref: '#/definitions/odontologo.OdontologoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: update odontologo for field
      tags:
      - odontologo
  /pacientes:
    post:
      consumes:
      - application/json
      description: Create a new paciente
      parameters:
      - description: Add paciente
        in: body
        name: Paciente
        required: true
        schema:
          $ref: '#/definitions/paciente.PacienteRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Create Paciente
      tags:
      - paciente
  /pacientes/:id:
    delete:
      consumes:
      - application/json
      description: Delete paciente by id
      parameters:
      - description: id del paciente
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: delete paciente
      tags:
      - paciente
    get:
      consumes:
      - application/json
      description: Get paciente by id
      parameters:
      - description: id del paciente
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: get paciente
      tags:
      - paciente
    put:
      consumes:
      - application/json
      description: Update paciente by id
      parameters:
      - description: Update paciente
        in: body
        name: Paciente
        required: true
        schema:
          $ref: '#/definitions/paciente.PacienteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: update paciente
      tags:
      - paciente
  /pacientes/patch/:id:
    patch:
      consumes:
      - application/json
      description: Update paciente for field
      parameters:
      - description: Add paciente for field
        in: body
        name: Paciente
        required: true
        schema:
          $ref: '#/definitions/paciente.PacienteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: update paciente for field
      tags:
      - paciente
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping
      tags:
      - example
  /turnos:
    post:
      consumes:
      - application/json
      description: Create a new turno
      parameters:
      - description: Add turno
        in: body
        name: Turno
        required: true
        schema:
          $ref: '#/definitions/turno.TurnoRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Create Turno
      tags:
      - turno
  /turnos/:id:
    delete:
      consumes:
      - application/json
      description: Delete turno by id
      parameters:
      - description: id del turno
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: delete turno
      tags:
      - turno
    get:
      consumes:
      - application/json
      description: Get turno by id
      parameters:
      - description: id del turno
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: turno example
      tags:
      - turno
    put:
      consumes:
      - application/json
      description: Update turno by id
      parameters:
      - description: Update turno
        in: body
        name: Turno
        required: true
        schema:
          $ref: '#/definitions/turno.TurnoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: update turno
      tags:
      - turno
  /turnos/dni:
    post:
      consumes:
      - application/json
      description: Create a new turno by DNI and Matricula
      parameters:
      - description: Add turno by dni and matricula
        in: body
        name: Turno
        required: true
        schema:
          $ref: '#/definitions/turno.TurnoDniMatriculaRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Create Turno By DNI and Matricula
      tags:
      - turno
  /turnos/dni/:id:
    get:
      consumes:
      - application/json
      description: Get turno by dni
      parameters:
      - description: dni del paciente
        in: path
        name: dni
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: get turno by dni
      tags:
      - turno
  /turnos/patch/:id:
    patch:
      consumes:
      - application/json
      description: Update turno for field
      parameters:
      - description: Update turno for field
        in: body
        name: Turno
        required: true
        schema:
          $ref: '#/definitions/turno.TurnoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: update turno for field
      tags:
      - turno
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
